name: Playwright Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: List directory contents
      run: ls -R
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/firstTest/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Change to Playwright directory
      run: cd firstTest && mvn -B install -DskipTests --no-transfer-progress
      
    - name: Ensure browsers are installed
      run: cd firstTest && mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

    - name: Install Extent Reports dependency
      run: cd firstTest && mvn install -DskipT  ests

    - name: Generate Extent Reports
      run: cd firstTest && mvn test > target/surefire-reports/extent-report.log 2>&1

    - name: Upload Extent Report (Optional)
      uses: actions/upload-artifact@v3
      with:
          path: target/surefire-reports/extent-report.html  # Change if your report location differs
          name: Extent Report
